name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
            set -e
            echo "ðŸš€ Deploy started"

            source ~/.bashrc

            echo "Node: $(node -v)"
            echo "NPM: $(npm -v)"

            cd /home/ubuntu/clinicXpert/clinic-expert-backend
            git pull origin main

            echo "ðŸ“¦ Backend"
            npm install
            npx prisma migrate dev --name added-document-support
            npx prisma generate || true

            echo "ðŸŒ Frontend"
            cd ../clinicxpert-frontend/
            git pull origin main
            npm install
            npm run build

            pm2 save
            echo "âœ… Deploy finished"
          EOF
